### ISSUE TITLE
Build fails on create-react-app

### ISSUE THREAD

**Issue by hammadfauz** [jefflau/jest-fetch-mock#59] opened 2018-04-02 19:43 UTC
`yarn build` fails with the following output:
```
Failed to minify the code from this file:

        ./node_modules/jest-fetch-mock/src/index.js:11

Read more here: http://bit.ly/2tRViJ9
```

**Comment by jefflau** [comment] 2018-04-03 03:44
Hmm. I'm not a yarn user so I'm not sure what the issue is exactly

**Comment by jefflau** [comment] 2018-04-03 03:47
Ah, it could be the fact that this package uses ES6 by default and create react app might assume it's ES5. But you probably shouldn't be building this package in products since it's just a mocking library. Maybe you can move your `jest-fetch-mock` dependency to dev dependencies and then CRA won't build it?

**Comment by hammadfauz** [comment] 2018-04-04 09:39
I agree that it shouldn't build in prod. I moved it to dev dependencies, but CRA still seems to be building it. Guess I'll open an issue there then. Thanks!

**Comment by jefflau** [comment] 2018-05-23 05:50
I'm closing this issue. Let me know if it's still a problem

**Closed by jefflau** 2018-05-23 05:50 UTC
